### ISSUE TITLE
Add EntitiesQuery

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org-database-layer#144]
### Todos

- [x] Filter out the following types in the SQL query (the `type` is stored in the sql table `type`):

```
+-----------------------------------------+
| name                                    |
+-----------------------------------------+
| applet                                  |
| article                                 |
| course                                  |
| text-exercise                           |
| text-exercise-group                     |
| video                                   |
+-----------------------------------------+
```

- [x] Filter out trashed objects (the property `trashed` is stored in the column `uuid.trashed`)
- [x] Filter out entities from a configurable list of taxonomies / the following construct can help: https://github.com/serlo/serlo.org-database-layer/blob/099c7241b3bbc8f36e3ebc1c6e1b0f2bf629e669/src/uuid/model/taxonomy_term.rs#L168-L197
  - [x] Everything under https://de.serlo.org/community/87993/community (`taxonomy_term.id == 87993`) besides everything under https://de.serlo.org/community/106081/neue-f%C3%A4cher-und-themen (`taxonomy_term.id == 106081`)
  - [x] Everything under https://de.serlo.org/informatik/75211/baustelle (`taxonomy_term.id == 75211`)
- [x] Add Parameter "instance" (optional) which filters for the instance (= column `instance.subdomain`)
- [x] Parameter "first" which determine the number of returned values (should be smaller then 10_000, otherwise there shall be an error)
- [x] Add Parameter "lastModified" and return only entites last modified after this date

Note: There a still things to consider before we can finish this task. However we know for sure that we need the above features.

**Comment by hugotiburtino** [comment]
- [X] Add feature tests

**Comment by kulla** [comment]
The output shall be changed from a dict of the form `{ entityIds: number[] }` to a dict `{ entitties: object[] }`. The objects shall the same as in https://nbviewer.org/github/serlo/evaluations/blob/2f19c47fa4ca91cb80ac77f29407edf1f6c3f617/Export%20of%20metadata%20to%20BIRD.ipynb#Fetching-metadata-from-the-DB The code also contains SQL statements and methods how to compute the values.
