### ISSUE TITLE
☂️ Umbrella Issue: CI

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org-database-layer#37]
- [x] For all pushes:
  - [x] Lint (cargo clippy)
  - [x] Build
  - [x] Pacts
- [x] For pushes to master
  - [x] Deploy (with our typical update_version
  - [x] Verify contracts

Probably the most annoying thing will be to init the database and wait for it before building / running contract tests.

**Comment by elbotho** [comment]
> Probably the most annoying thing will be to init the database and wait for it before building / running contract tests.

Would it be worth it to make a tiny subset with the data just for the tests?

**Comment by inyono** [comment]
Don't think that this is needed (especially since it would writing unit tests more annoying). Since we need a database for the tests anyways, the SQL import step itself isn't a problem.
