### ISSUE TITLE
☂️ Umbrella Issue: POST endpoints

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org-database-layer#47]
[Contract](https://pact.serlo.org/pacts/provider/serlo.org/consumer/api.serlo.org/latest)

- [x] `/set-uuid-state` #27
- [x] `/thread/set-archive` #46
- [x] `/thread/start-thread` #49
- [x] `/thread/comment-thread` #50
- [x] `/set-notification-state` #48

**Comment by elbotho** [comment]
🎉 thanks for finishing this!
