### ISSUE TITLE
☂️ Umbrella Issue: GET endpoints

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org-database-layer#5]
[Contract](https://pact.serlo.org/pacts/provider/serlo.org/consumer/api.serlo.org/latest)

- [x] `/alias/{alias}` #11
- [x] `/event/{id}`#12
- [x] `/license/{id}` #20
- [x] `/notifications/{user_id}` #14
- [x] `/subscriptions/{user_id}` #8
- [x] `/threads/{id}` #7
- [x] `/user/active-authors` #9
- [x] `/user/active-reviewers` #10
- [x] `/uuid/{id}` #6
- [x] `/navigation` #13
